[package]
name = "stegopass"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10"
arboard = "3.5.0"
argon2 = "0.5"
clap = { version = "4.4", features = ["derive"] }
image = "0.25.6"
password-hash = "0.5"
rand = "0.9.1"
rpassword = "7.4.0"
sha2 = "0.10"
tempfile = "3.20.0"
